# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  one:
    docker:
      - image: jino7varghese/rhel7-apache
    steps:
      - checkout
      - run: echo "Downloading Apache PAS container...Done."
      - run: mkdir -p PAS_workspace
      - run: echo "Trying out workspaces" > PAS_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: PAS_workspace
          # Must be relative path from root
          paths:
            - echo-output    
      - run: pwd
      - run: ls -lah
      - run: uname -a
  two:
    steps:
      - checkout
      - run: echo "Lets check python Script."  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: PAS_workspace

      - run: |
          if [[ $(cat PAS_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
      - run: python --version
      - run: python version_manager.py -l fix	

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
